version: "3.8"

services:
    php:
        volumes:
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    nginx:
        ports:
            - "8881:80"
        working_dir: /var/www/app
        volumes:
            - ./nginx/development/conf.d:/etc/nginx/conf.d/

    mysql:
        ports:
            - "33067:3306"
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=lumiere