version: "3.8"

services:
    php:
        volumes:
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    nginx:
        ports:
            - "8889:80"
        working_dir: /var/www/app
        volumes:
            - ./nginx/development/conf.d:/etc/nginx/conf.d/

    mysql:
        ports:
            - "33060:3306"